![torchman](../Practice/imgs/torchman.jpg)

이번 차례에는 머신러닝 파이프라인을 살펴보고 데이터를 어떻게 텐서를 통해 표현하는지 살펴보겠습니다  

# Deep learning pipeline

![dlpl](../Practice/imgs/pipelin.png)

저희가 지금까지 배운 수 체계에는 스칼라, 벡터, 행렬, 텐서가 있었습니다.  
그리고 많은 머신러닝 책에서는 아래와 같이 표기합니다.  
여러 모듈과 메소드를 통해 파이토치에서 어떻게 텐서를 조작하는지 알아보겠습니다  

[https://pytorch.org/](https://pytorch.org/)

git clone https://github.com/SunCreation/pytorch_master.git

In [1]:
import torch as th

$${스칼라 : x \quad  }$$
$$벡터 : \mathbf x \quad n  $$
$$행렬 : \mathbf X \quad m \times n  $$
$$텐서 : \mathcal {X} \quad l \times m \times n \times \dots $$

먼저 들어가기 앞서서 프로그래밍 초반에 배우는 데이터의 타입을 떠올려보겠습니다.  
대표적으로 다음과 같습니다. 
1. Int  
2. Double  
3. Float  

일반적으로 torch의 여러가지 텐서모듈을 통해 위의 데이터타입을 가지는 텐서를 생성할 수 있습니다 

In [2]:
from torch import tensor
from torch import FloatTensor as ftensor
from torch import DoubleTensor as dtensor

텐서 객체는 다음과 같은 형태로 할당하게 됩니다.  
tensor = tensor(data, dtype=float32, device='cpu')  
텐서 객체를 생성하기 위한 파라미터와 인자는 data, dtype, device가 있습니다.  


## 1. 스칼라

dtype과 device를 지정하지 않으면 자동으로 dtype을 식별하고 device는 cpu로 할당하게 됩니다.   

.item()을 통하여 텐서 객체 내의 단일 스칼라 값을 뽑아낼 수 있습니다. item 메소드는 반드시 스칼라 텐서에서 호출해야 합니다

In [3]:
scalar = th.tensor(0.1)
type(scalar.item())

float

## 2. 벡터

In [4]:
import numpy as np
nparray = np.zeros((1, 2, 3))
vector = th.tensor(nparray)
vector

tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [5]:
vec1 = tensor([1, 2, 3, 4])
vec2 = dtensor([1, 2, 3 ,4])
vec3 = ftensor([1, 2, 3, 4])

In [7]:
print(vec1, vec2, vec3)

tensor([1, 2, 3, 4]) tensor([1., 2., 3., 4.], dtype=torch.float64) tensor([1., 2., 3., 4.])


data에 들어갈 수 있는 컨테이너는 List, Tuple, Numpy array입니다.  
파이토치에서 텐서 객체를 만드는 방법은 기존의 numpy와 매우 유사합니다.  

In [11]:
# 리스트 컴프리헨션으로 100개의 텐서를 리스트에 넣으세요.
tensor_q = [tensor([x]) for x in range(100)]

## 3. 행렬

이제 행렬 텐서를 만들어보겠습니다.  
데이터타입을 행렬로 다루기 시작한다면 device를 gpu로 지정하는게 좋습니다.  
이제 데이터를 일일히 생성하기 힘드므로 rand를 사용하겠습니다.  
rand를 잘 활용하기 위해 시드를 고정하겠습니다.  

![tensor](../Practice/imgs/tensor.png)

In [23]:
th.manual_seed(1234)
mat = th.rand((2, 2))
mat1 = th.rand(2, 2)
mat, mat1

(tensor([[0.0290, 0.4019],
         [0.2598, 0.3666]]),
 tensor([[0.0583, 0.7006],
         [0.0518, 0.4681]]))

## 4. 텐서  
이제 3차원 이상의 텐서를 만들어보겠습니다.  

In [26]:
mat3 = th.rand(3, 4, 5)

In [27]:
mat3

tensor([[[0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
         [0.4517, 0.4757, 0.7842, 0.1525, 0.6662],
         [0.3343, 0.7893, 0.3216, 0.5247, 0.6688]],

        [[0.8436, 0.4265, 0.9561, 0.0770, 0.4108],
         [0.0014, 0.5414, 0.6419, 0.2976, 0.7077],
         [0.4189, 0.0655, 0.8839, 0.8083, 0.7528],
         [0.8988, 0.6839, 0.7658, 0.9149, 0.3993]],

        [[0.1100, 0.2541, 0.4333, 0.4451, 0.4966],
         [0.7865, 0.6604, 0.1303, 0.3498, 0.3824],
         [0.8043, 0.3186, 0.2908, 0.4196, 0.3728],
         [0.3769, 0.0108, 0.9455, 0.7661, 0.2634]]])

# 퀴즈 (Easy)  
1) !nvidia-smi 를 통해 현재 gpu의 메모리 사용량을 확인하세요
2) 크기가 (100, 100, 100)인 3차원 랜덤 텐서를 gpu 메모리에 할당하세요
3) 다시 !nvidia-smi를 통해 gpu 메모리 사용량이 얼마나 늘었는지 계산해보세요

In [28]:
! nvidia-smi 

Fri Jun 24 10:57:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P0    21W /  N/A |      5MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [29]:
mat4 = th.rand(100, 100, 100)

In [31]:
tensor(mat4, device = 'cuda')

/tmp/ipykernel_17643/2718875410.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor(mat4, device = 'cuda')


tensor([[[0.1880, 0.5174, 0.7849,  ..., 0.8757, 0.7378, 0.9949],
         [0.2338, 0.2153, 0.2073,  ..., 0.9475, 0.9515, 0.5817],
         [0.2920, 0.8040, 0.4826,  ..., 0.1071, 0.0648, 0.6555],
         ...,
         [0.7855, 0.1410, 0.9706,  ..., 0.1771, 0.9385, 0.0165],
         [0.7791, 0.1056, 0.2174,  ..., 0.0187, 0.4807, 0.9493],
         [0.4512, 0.4553, 0.6969,  ..., 0.3192, 0.1100, 0.9460]],

        [[0.3930, 0.8984, 0.0452,  ..., 0.1375, 0.9205, 0.1624],
         [0.3788, 0.4968, 0.6348,  ..., 0.0284, 0.4027, 0.5966],
         [0.8497, 0.3773, 0.8951,  ..., 0.9170, 0.6660, 0.1428],
         ...,
         [0.2665, 0.5249, 0.4629,  ..., 0.1564, 0.4731, 0.1355],
         [0.6756, 0.1651, 0.8155,  ..., 0.7816, 0.1069, 0.7070],
         [0.2158, 0.1250, 0.4128,  ..., 0.7782, 0.0969, 0.2174]],

        [[0.0680, 0.6999, 0.3438,  ..., 0.9838, 0.7281, 0.2104],
         [0.3052, 0.9725, 0.6939,  ..., 0.5454, 0.1958, 0.2802],
         [0.8390, 0.6447, 0.2936,  ..., 0.3189, 0.8806, 0.

In [32]:
! nvidia-smi 

Fri Jun 24 11:01:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P0    31W /  N/A |    989MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

5MiB에서 989MiB로 값이 바뀌는 것을 확인함

In [39]:
th.cuda.empty_cache( )

In [40]:
! nvidia-smi 

Fri Jun 24 11:09:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8     6W /  N/A |    988MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [41]:
mat4 del tensor

SyntaxError: invalid syntax (1437800297.py, line 1)

In [ ]:
torch.cuda.empty_cache( )