![torchman](imgs/torchman.jpg)

이번 차례에는 머신러닝 파이프라인을 살펴보고 데이터를 어떻게 텐서를 통해 표현하는지 살펴보겠습니다  














# Deep learning pipeline

![dlpl](imgs/pipelin.png)



저희가 지금까지 배운 수 체계에는 스칼라, 벡터, 행렬, 텐서가 있었습니다.  
그리고 많은 머신러닝 책에서는 아래와 같이 표기합니다.  
여러 모듈과 메소드를 통해 파이토치에서 어떻게 텐서를 조작하는지 알아보겠습니다  

[https://pytorch.org/](https://pytorch.org/)

In [2]:
import torch as th

$${스칼라 : x \quad  }$$
$$벡터 : \mathbf x \quad n  $$
$$행렬 : \mathbf X \quad m \times n  $$
$$텐서 : \mathcal {X} \quad l \times m \times n \times \dots $$

![tensor](imgs/tensor.png)

먼저 들어가기 앞서서 프로그래밍 초반에 배우는 데이터의 타입을 떠올려보겠습니다.  
대표적으로 다음과 같습니다. 
1. Int  
2. Double  
3. Float  

일반적으로 torch의 여러가지 텐서모듈을 통해 위의 데이터타입을 가지는 텐서를 생성할 수 있습니다 

In [1]:
from torch import tensor
from torch import FloatTensor as ftensor
from torch import DoubleTensor as dtensor

텐서 객체는 다음과 같은 형태로 할당하게 됩니다.  
tensor = tensor(data, dtype=float32, device='cpu')  
텐서 객체를 생성하기 위한 파라미터와 인자는 data, dtype, device가 있습니다.  


## 1. 스칼라

dtype과 device를 지정하지 않으면 자동으로 dtype을 식별하고 device는 cpu로 할당하게 됩니다.   

.item()을 통하여 텐서 객체 내의 단일 스칼라 값을 뽑아낼 수 있습니다. item 메소드는 반드시 스칼라 텐서에서 호출해야 합니다

## 2. 벡터

In [4]:
import numpy as np

data에 들어갈 수 있는 컨테이너는 List, Tuple, Numpy array입니다.  
파이토치에서 텐서 객체를 만드는 방법은 기존의 numpy와 매우 유사합니다.  

## 3. 행렬

이제 행렬 텐서를 만들어보겠습니다.  
데이터타입을 행렬로 다루기 시작한다면 device를 gpu로 지정하는게 좋습니다.  
이제 데이터를 일일히 생성하기 힘드므로 rand를 사용하겠습니다.  
rand를 잘 활용하기 위해 시드를 고정하겠습니다.  

## 4. 텐서  
이제 3차원 이상의 텐서를 만들어보겠습니다.  

# 퀴즈 (Easy)  
1) !nvidia-smi 를 통해 현재 gpu의 메모리 사용량을 확인하세요
2) 크기가 (100, 100, 100)인 3차원 랜덤 텐서를 gpu 메모리에 할당하세요
3) 다시 !nvidia-smi를 통해 gpu 메모리 사용량이 얼마나 늘었는지 계산해보세요

In [ ]:
!nvidia-smi

# 5. 텐서의 연산


In [12]:
vec1 = tensor([1,2,3])
vec2 = tensor([4,5,6])

In [13]:
vec3 = vec1.dot(vec2)
# @ = matmul
vec3

tensor(32)

In [14]:
cross_vec = th.cross(vec1,vec2)
print(cross_vec)

tensor([-3,  6, -3])


In [15]:
print(vec1 * vec2)

tensor([ 4, 10, 18])


In [16]:
mat1 = tensor([[1,2],[3,4]])
mat2 = tensor([[5,6],[7,8]])
print(mat1 * mat2)

tensor([[ 5, 12],
        [21, 32]])


In [17]:
mat1 @ mat2

tensor([[19, 22],
        [43, 50]])